runtime: php55
api_version: 1

# Static Files Cache
default_expiration: "10d"

handlers:

# Order Matters - top first match will be selected
- url: /(.+\.(gif|png|jpg|css|js|txt|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|txt|ico)$
  secure: always

# Custom jeep page
- url: /jeep
  script: custompages/jeep.php
  secure: always

# Custom jeep page
- url: /billing
  script: custompages/billing.php
  secure: always

# Main site pages
- url: /.*
  script: index.php
  secure: always
